<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    //IM EVENT REPO WERDEN select & from AUTOMATISCH GEMACHT
    public function findByBerlin(){
        $builder = $this->createQueryBuilder('e');
        $builder->andWhere('e.city=:c')
            ->setParameter('c', 'Berlin');
        return $builder->getQuery()->getResult();
    }
}
